### ISSUE TITLE
Agregar resolución al pie de página

### ISSUE THREAD

**Issue by eugesma** [andes/recetar-app#13]
Agregar resolución al pie de páigina del PDF generado con la receta.

**Comment by sychus** [comment]
@eugesma , se me ocurre que además de hacer referencia al número de la resolución. Se podría poner el link a donde la pueden leer.

**Comment by eugesma** [comment]
Tal cuál, quizás dejarlo fijo como footer en todas las páginas, aún sin autenticar.
