### ISSUE TITLE
Historial

### ISSUE THREAD

**Issue by sychus** [andes/recetar-app#15]
El profesional debería poder acceder a un Historial de recetas dispensadas.
Casos de Uso:
a) Poder enviar la receta por algún otro medio o imprimir y firmar.
b) Visualizar y tener un control sobre si su receta fue o no dispensada. (no es necesario que sepa por quien)
c) Poder verificar (search) si ya hizo esa receta para ese paciente. ;-)

Agregar una ventana adicional o sidebar. Donde el médico tenga las últimas 10 recetas generadas. Realizar esta funcionalidad del lado de la API (usar skip & limit). Permitir scroll infinito.

**Comment by eugesma** [comment]
falta:
- Imprimir
- Filtrar
- Traer solo ultimas 10 con infinite scrolling.

**Comment by eugesma** [comment]
falta: 
- Filtrar
- Traer solo ultimas 10 con infinite scrolling.

**Comment by sychus** [comment]
@eugesma @paul18sma , se me ocurre que podríamos agregar en este caso (un botón editar y otro eliminar) dentro de cada elemento del historial de recetas siempre y cuando estén pendientes.
