### ISSUE TITLE
Agregar campos para recetas de psicotrópicos

### ISSUE THREAD

**Issue by eugesma** [andes/recetar-app#2]
- Agregar campos con códigos para recetas de psicotrópicos.

**Comment by eugesma** [comment]
Relevar...

**Comment by sychus** [comment]
¿Esto que sería?

**Comment by eugesma** [comment]
Romina había mencionado en cierto momento que las recetas de psicotrópicos se hacían por triplicado y cada una llevaba un código específico... Capaz es irrelevante
