### ISSUE TITLE
Retornar acción

### ISSUE THREAD

**Issue by eugesma** [andes/recetar-app#3]
Tanto como para el farmacéutico (dispensar) como para el médico (crear), luego de haber realizado la acción, mostrar un botón con contador de tiempo, quizás 5 minutos, para poder retornar la acción.
Para realizar esto, sería importante tener en cuenta un seguimiento de los movimientos realizados del lado del usuario y del objeto.

**Comment by sychus** [comment]
@eugesma tal vez para evitar esto, se podría usar la misma pantalla de Historia (#15) y que permita editar la receta hasta que la misma sea dispensada. Una vez dispensada no puede ser modificada nunca más. ¿Les parece?

**Comment by eugesma** [comment]
@sychus si, sería más fácil. Y para el caso de dispensación errada del lado farmacia?

**Comment by sychus** [comment]
> @sychus si, sería más fácil. Y para el caso de dispensación errada del lado farmacia?

Se me ocurre algo más sencillo como un botón deshacer, en este caso hay que pensar bien cual sería el deadline de esta acción. Ya que no hay ninguna otra que la valide o invalide. Y puede pasar que sea un punto de falla para dispensar el medicamento más de una vez. ¿A alguno se le ocurre alguna otra idea?

**Comment by eugesma** [comment]
Quizás con un tiempo prudencial de 30 min. estaría bien.

**Comment by eugesma** [comment]
120 min según lo relevado en última reunón.
